name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jeongsk/Github-CodeReviewBot@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LAAS_API_KEY: ${{ secrets.LAAS_API_KEY }}